version: '3'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    depends_on:
      - pgdb
  pgdb:
    image: postgres
    container_name: pgdb
      POSTGRES_DB=django
      POSTGRES_USER=django
      POSTGRES_PASSWORD=eps19